user: admin
passwd: admin
url: http://localhost:8080
loginurl: http://localhost:8080/share
browser: firefox
photopath: images
cmisurl: /alfresco/api/-default-/public/cmis/versions/1.1/browser
ftpurl: localhost
ftpport: 2021
imap_host: localhost
imap_port: 8143
