user: admin
passwd: admin
url: https://docs.digcat.com
browser: firefox
cmisurl: /alfresco/api/-default-/public/cmis/versions/1.1/browser 
ftpurl: docs.digcat.com
ftpport: 2021
ftpsrc: /Alfresco/Sites/swsdp/documentLibrary/Presentations
ftpsrcfile: Project Overview.ppt
imap_host: docs.digcat.com
imap_port: 8143
