user: admin
passwd: admin
url: https://docs.digcat.com
browser: firefox
cmisurl: /alfresco/cmisatom
ftpurl: 192.168.1.145
ftpport: 2021
ftpsrc: /Alfresco/Sites/swsdp/documentLibrary/Presentations
ftpsrcfile: Project Overview.ppt
imap_host: docs.digcat.com
imap_port: 8143
