user: admin
passwd: admin
url: http://docs.digcat.com:8080
loginurl: http://docs.digcat.com:8080/share
browser: phantomjs
photopath: images
addons: rm,jsconsole,share_site_creators
cmisurl: /alfresco/api/-default-/public/cmis/versions/1.1/browser
ftpurl: docs.digcat.com
ftpport: 2021
imap_host: docs.digcat.com
imap_port: 8143
