user: admin
passwd: admin 
sharehost: 104.238.174.54 
shareport: 8080
repohost: 104.238.174.54
repoport: 8081
https: false
loginurl: /share
browser: firefox
photopath: images
cmisurl: /alfresco/api/-default-/public/cmis/versions/1.1/browser
cmisatom: /alfresco/cmisatom
ftpport: 2021
imap_host: localhost
imap_port: 8143
